# coding: utf-8

"""
    BugSeq

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bugseq_client.openapi_client.models.billing_account_sample_credit_response import BillingAccountSampleCreditResponse

class TestBillingAccountSampleCreditResponse(unittest.TestCase):
    """BillingAccountSampleCreditResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingAccountSampleCreditResponse:
        """Test BillingAccountSampleCreditResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingAccountSampleCreditResponse`
        """
        model = BillingAccountSampleCreditResponse()
        if include_optional:
            return BillingAccountSampleCreditResponse(
                id = '',
                sample_type = 'metagenomic',
                initial_count = 56,
                remaining_count = 56,
                expiration = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                billing_account_id = '',
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return BillingAccountSampleCreditResponse(
                id = '',
                sample_type = 'metagenomic',
                initial_count = 56,
                remaining_count = 56,
                expiration = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                billing_account_id = '',
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testBillingAccountSampleCreditResponse(self):
        """Test BillingAccountSampleCreditResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
