from ..DataModel import DataModel as DataModel
from ..styles.FillStyle import FillStyle as FillStyle
from ..styles.LineStyle import LineStyle as LineStyle
from dataclasses import dataclass, field
from dataclasses_json import config
from strenum import StrEnum

class GeosteerHorizonRole(StrEnum):
    Default = 'Default'
    ZoneTop = 'ZoneTop'
    ZoneBottom = 'ZoneBottom'
    AnalysisTop = 'AnalysisTop'
    AnalysisBase = 'AnalysisBase'
    TargetTop = 'TargetTop'
    TargetBase = 'TargetBase'

@dataclass
class Horizon(DataModel):
    role: GeosteerHorizonRole = ...
    formation_id: int = ...
    show: bool = ...
    line_style: LineStyle | None = ...
    fill_style: FillStyle | None = ...
    zone_name: str | None = ...
    defines_zone: bool | None = ...
    def get_line_color(self) -> str: ...

@dataclass
class TypewellHorizonDepth(DataModel):
    type_wellbore_id: int = ...
    horizon_id: int = ...
    md: float = field(default=0.0, metadata=config(field_name='MD'))
    tvd: float = field(default=0.0, metadata=config(field_name='TVD'))
    tvt: float = field(default=0.0, metadata=config(field_name='TVT'))
    @property
    def key(self) -> str: ...
    @staticmethod
    def make_key(type_wellbore_id: int, horizon_id: int) -> str: ...
