"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .authtoken import AuthToken, AuthTokenTypedDict
from cribl_control_plane.types import BaseModel
from typing import Dict, List
from typing_extensions import TypedDict


class LoginResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: AuthTokenTypedDict


class LoginResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: AuthToken
