# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.get_project_device_public_keys200_response import (
    GetProjectDevicePublicKeys200Response,
)


class TestGetProjectDevicePublicKeys200Response(unittest.TestCase):
    """GetProjectDevicePublicKeys200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProjectDevicePublicKeys200Response:
        """Test GetProjectDevicePublicKeys200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetProjectDevicePublicKeys200Response`
        """
        model = GetProjectDevicePublicKeys200Response()
        if include_optional:
            return GetProjectDevicePublicKeys200Response(
                device_public_keys = [
                    notehub_py.models.get_project_device_public_keys_200_response_device_public_keys_inner.getProjectDevicePublicKeys_200_response_device_public_keys_inner(
                        key = '', 
                        uid = '', )
                    ],
                has_more = True
            )
        else:
            return GetProjectDevicePublicKeys200Response(
                device_public_keys = [
                    notehub_py.models.get_project_device_public_keys_200_response_device_public_keys_inner.getProjectDevicePublicKeys_200_response_device_public_keys_inner(
                        key = '', 
                        uid = '', )
                    ],
                has_more = True,
        )
        """

    def testGetProjectDevicePublicKeys200Response(self):
        """Test GetProjectDevicePublicKeys200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
