from enum import Enum


class SimulationStateType0(str, Enum):
    ADAPTATION_COMPLETE = "ADAPTATION_COMPLETE"
    ADAPTATION_FAILED = "ADAPTATION_FAILED"
    ADAPTATION_IN_PROGRESS = "ADAPTATION_IN_PROGRESS"
    ADAPTATION_WAITING_TO_START = "ADAPTATION_WAITING_TO_START"
    DRAFT = "DRAFT"
    EVALUATION_COMPLETE = "EVALUATION_COMPLETE"
    EVALUATION_FAILED = "EVALUATION_FAILED"
    EVALUATION_IN_PROGRESS = "EVALUATION_IN_PROGRESS"
    EVALUATION_PARTIALLY_COMPLETE = "EVALUATION_PARTIALLY_COMPLETE"
    EXPERIMENT_COMPLETED = "EXPERIMENT_COMPLETED"
    EXPERIMENT_FAILED = "EXPERIMENT_FAILED"
    EXPERIMENT_PARTIALLY_COMPLETE = "EXPERIMENT_PARTIALLY_COMPLETE"
    EXPERIMENT_STARTED = "EXPERIMENT_STARTED"
    GENERATION_COMPLETE = "GENERATION_COMPLETE"
    GENERATION_FAILED = "GENERATION_FAILED"
    GENERATION_IN_PROGRESS = "GENERATION_IN_PROGRESS"
    QUEUED = "QUEUED"
    VALIDATION_COMPLETE = "VALIDATION_COMPLETE"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    VALIDATION_IN_PROGRESS = "VALIDATION_IN_PROGRESS"
    VALIDATION_PARTIALLY_COMPLETE = "VALIDATION_PARTIALLY_COMPLETE"

    def __str__(self) -> str:
        return str(self.value)
