"""Zora API schema constants for data field names."""

ZORA_COIN_ID = "zora_coin_id"
ZORA_COIN_URI = "zora_token_uri"
ZORA_CHAIN_ID = "zora_chain_id"
ZORA_NAME = "zora_name"
ZORA_DESCRIPTION = "zora_description"
ZORA_ADDRESS = "zora_address"
ZORA_SYMBOL = "zora_symbol"
ZORA_TOTAL_SUPPLY = "zora_total_supply"
ZORA_TOTAL_VOLUME = "zora_total_volume"
ZORA_VOLUME_24H = "zora_volume_24h"
ZORA_CREATED_AT = "zora_created_at"
ZORA_CREATOR_ADDRESS = "zora_creator_address"
ZORA_PRICE_IN_USDC = "zora_price_in_usdc"
ZORA_MARKET_CAP = "zora_market_cap"
ZORA_MARKET_CAP_DELTA_24H = "zora_market_cap_delta_24h"
ZORA_UNIQUE_HOLDERS = "zora_unique_holders"
ZORA_PLATFORM_REFERRER_ADDRESS = "zora_platform_referrer_address"
ZORA_PAYOUT_RECIPIENT_ADDRESS = "zora_payout_recipient_address"
ZORA_CREATOR_FARCASTER_ID = "zora_creator_farcaster_id"
ZORA_MEDIA_CONTENT_TYPE = "zora_media_content_type"
ZORA_MEDIA_CONTENT_URL = "zora_media_content_url"
ZORA_PREVIEW_SMALL_URL = "zora_preview_small_url"
ZORA_PREVIEW_MEDIUM_URL = "zora_preview_medium_url"
ZORA_UPDATED_AT = "zora_updated_at"
