# coding: utf-8

"""
    Platform API

    _OpenAPI specification for the **Platform API** of **Helix**, the nomination platform of ElecLink_  ---  Additional documentation available in the API's [GitHub repository](https://github.com/eleclink-helix/platform-api) 

    The version of the OpenAPI document: 1.2.0
    Contact: team.eleclink@eleclink.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class Timescale(str, Enum):
    """
    Timescale
    """

    """
    allowed enum values
    """
    LONG_TERM = 'LONG_TERM'
    DAY_AHEAD = 'DAY_AHEAD'
    INTRA_DAY = 'INTRA_DAY'

    @classmethod
    def from_json(cls, json_str: str) -> Timescale:
        """Create an instance of Timescale from a JSON string"""
        return Timescale(json.loads(json_str))


