from .nav_panel_PIPELINE1 import nav_panel_PIPELINE1_ui, nav_panel_PIPELINE1_server, PIPELINE1_description
from .nav_panel_PIPELINE2 import nav_panel_PIPELINE2_ui, nav_panel_PIPELINE2_server, PIPELINE2_description
from .nav_panel_PIPELINE3 import nav_panel_PIPELINE3_ui, nav_panel_PIPELINE3_server, PIPELINE3_description
from .nav_panel_PIPELINE4 import nav_panel_PIPELINE4_ui, nav_panel_PIPELINE4_server, PIPELINE4_description
from .nav_panel_PIPELINE5 import nav_panel_PIPELINE5_ui, nav_panel_PIPELINE5_server, PIPELINE5_description
