STOCK_PICKING_DIRECTION_FIXER = {
    17: 4,
    1: 3,
}


STOCK_PICKING_SEND_FLAG_FIXER = {17: "0", 1: "", 5: ""}

PICKING_TYPE_FIXER = {
    17: "outgoing",
    6: "store",
}

ODOO_KARDEX_UNIT_FIXER = {
    "Einheit(en)": "Stk",
}

PICKING_AUTO = True

PICKING_DATE_HANDLING = "send"  # or 'create'

START_STOCK_SYNC = 72000000

KARDEX_WAREHOUSE = "Kardex"
KARDEX_DESTINATION = "Kardex"
PALETTEN_WAREHOUSE = "Paletten"
AGGREGATE_PALETTEN = False
NON_KARDEX_WAREHOUSE = "Bestand"
STOCK_WAREHOUSE = "Bestand"
INCOMING_WAREHOUSE = "Eingang"


USE_KARDEX_AS_DEFAULT_WAREHOUSE = False

COMPANY_ID = 1

OVERRIDE_SERIAL_FOR_STORE = True
CREATE_SERIAL_FOR_STORE = True

OVERRIDE_SERIAL_FOR_PRODUCTION = True
CREATE_SERIAL_FOR_PRODUCTION = True

CREATE_LOTS_AUTOMATICALLY = False

POST_PRODUCTION_LOCATION = "Nachproduktion"
ENTRANCE_LOCATION = "Eingang"

USE_BESTANDSABGLEICH_FOR_SYNC_STOCKS = False

TRANSFER_INVENTORY_MOVES = True
