from enum import Enum


class AlertResponseDataSource(str, Enum):
    ALERTMANAGER = "alertmanager"
    API = "api"
    APP_DYNAMICS = "app_dynamics"
    APP_OPTICS = "app_optics"
    ASANA = "asana"
    AZURE = "azure"
    BUG_SNAG = "bug_snag"
    CATCHPOINT = "catchpoint"
    CHECKLY = "checkly"
    CHRONOSPHERE = "chronosphere"
    CLICKUP = "clickup"
    CLOUD_WATCH = "cloud_watch"
    DATADOG = "datadog"
    EMAIL = "email"
    GENERIC_WEBHOOK = "generic_webhook"
    GITLAB = "gitlab"
    GOOGLE_CLOUD = "google_cloud"
    GRAFANA = "grafana"
    HONEYCOMB = "honeycomb"
    JIRA = "jira"
    LINEAR = "linear"
    LIVE_CALL_ROUTING = "live_call_routing"
    MANUAL = "manual"
    MONTE_CARLO = "monte_carlo"
    NAGIOS = "nagios"
    NEW_RELIC = "new_relic"
    NOBL9 = "nobl9"
    OPSGENIE = "opsgenie"
    PAGERDUTY = "pagerduty"
    PAGERTREE = "pagertree"
    PRTG = "prtg"
    ROLLBAR = "rollbar"
    ROOTLY = "rootly"
    SENTRY = "sentry"
    SERVICE_NOW = "service_now"
    SLACK = "slack"
    SPLUNK = "splunk"
    VICTOROPS = "victorops"
    WEB = "web"
    WORKFLOW = "workflow"
    ZENDESK = "zendesk"

    def __str__(self) -> str:
        return str(self.value)
