from kilojoule.templates.SI import *

p.set_units("kPa")
u.set_units("kJ/kg")
h.set_units("kJ/kg")
s.set_units("kJ/kg/K")
X.set_units("kJ")
Xdot.set_units("kW")
phi.set_units("kJ/kg")
psi.set_units("kJ/kg")
M.set_units("kg/kmol")
N.set_units("kmol")
R.set_units("kJ/kg/K")
c_v.set_units("kJ/kg/K")
c_p.set_units("kJ/kg/K")
