# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frequenz/api/common/metrics.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'frequenz/api/common/metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!frequenz/api/common/metrics.proto\x12\x1b\x66requenz.api.common.metrics\"&\n\x06\x42ounds\x12\r\n\x05lower\x18\x01 \x01(\x02\x12\r\n\x05upper\x18\x02 \x01(\x02\"\x9d\x02\n\x06Metric\x12\r\n\x05value\x18\x01 \x01(\x02\x12\x39\n\x0crated_bounds\x18\x02 \x01(\x0b\x32#.frequenz.api.common.metrics.Bounds\x12=\n\x10\x63omponent_bounds\x18\x03 \x01(\x0b\x32#.frequenz.api.common.metrics.Bounds\x12\x44\n\x17system_exclusion_bounds\x18\x04 \x01(\x0b\x32#.frequenz.api.common.metrics.Bounds\x12\x44\n\x17system_inclusion_bounds\x18\x05 \x01(\x0b\x32#.frequenz.api.common.metrics.Bounds\"\xee\x02\n\x11MetricAggregation\x12\x0b\n\x03\x61vg\x18\x01 \x01(\x02\x12\x10\n\x03min\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12\x10\n\x03max\x18\x03 \x01(\x02H\x01\x88\x01\x01\x12\x12\n\nraw_values\x18\x0c \x03(\x02\x12\x39\n\x0crated_bounds\x18\r \x01(\x0b\x32#.frequenz.api.common.metrics.Bounds\x12=\n\x10\x63omponent_bounds\x18\x0e \x01(\x0b\x32#.frequenz.api.common.metrics.Bounds\x12\x44\n\x17system_exclusion_bounds\x18\x04 \x01(\x0b\x32#.frequenz.api.common.metrics.Bounds\x12\x44\n\x17system_inclusion_bounds\x18\x05 \x01(\x0b\x32#.frequenz.api.common.metrics.BoundsB\x06\n\x04_minB\x06\n\x04_maxb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frequenz.api.common.metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOUNDS']._serialized_start=66
  _globals['_BOUNDS']._serialized_end=104
  _globals['_METRIC']._serialized_start=107
  _globals['_METRIC']._serialized_end=392
  _globals['_METRICAGGREGATION']._serialized_start=395
  _globals['_METRICAGGREGATION']._serialized_end=761
# @@protoc_insertion_point(module_scope)
