# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frequenz/api/common/v1/microgrid/microgrid.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'frequenz/api/common/v1/microgrid/microgrid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from frequenz.api.common.v1.grid import delivery_area_pb2 as frequenz_dot_api_dot_common_dot_v1_dot_grid_dot_delivery__area__pb2
from frequenz.api.common.v1 import location_pb2 as frequenz_dot_api_dot_common_dot_v1_dot_location__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0frequenz/api/common/v1/microgrid/microgrid.proto\x12 frequenz.api.common.v1.microgrid\x1a/frequenz/api/common/v1/grid/delivery_area.proto\x1a%frequenz/api/common/v1/location.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x02\n\tMicrogrid\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x15\n\renterprise_id\x18\x02 \x01(\x04\x12\x0c\n\x04name\x18\x03 \x01(\t\x12@\n\rdelivery_area\x18\x04 \x01(\x0b\x32).frequenz.api.common.v1.grid.DeliveryArea\x12\x32\n\x08location\x18\x05 \x01(\x0b\x32 .frequenz.api.common.v1.Location\x12\x41\n\x06status\x18\x06 \x01(\x0e\x32\x31.frequenz.api.common.v1.microgrid.MicrogridStatus\x12\x34\n\x10\x63reate_timestamp\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"D\n\x15MicrogridComponentIDs\x12\x14\n\x0cmicrogrid_id\x18\x01 \x01(\x04\x12\x15\n\rcomponent_ids\x18\x02 \x03(\x04\">\n\x12MicrogridSensorIDs\x12\x14\n\x0cmicrogrid_id\x18\x01 \x01(\x04\x12\x12\n\nsensor_ids\x18\x02 \x03(\x04*o\n\x0fMicrogridStatus\x12 \n\x1cMICROGRID_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n\x17MICROGRID_STATUS_ACTIVE\x10\x01\x12\x1d\n\x19MICROGRID_STATUS_INACTIVE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frequenz.api.common.v1.microgrid.microgrid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MICROGRIDSTATUS']._serialized_start=643
  _globals['_MICROGRIDSTATUS']._serialized_end=754
  _globals['_MICROGRID']._serialized_start=208
  _globals['_MICROGRID']._serialized_end=507
  _globals['_MICROGRIDCOMPONENTIDS']._serialized_start=509
  _globals['_MICROGRIDCOMPONENTIDS']._serialized_end=577
  _globals['_MICROGRIDSENSORIDS']._serialized_start=579
  _globals['_MICROGRIDSENSORIDS']._serialized_end=641
# @@protoc_insertion_point(module_scope)
