import datetime
from typing import Any

import pep249

# ─── Constants ────────────────────────────────────────────────────────────────

apilevel: str = ...
threadsafety: int = ...
paramstyle: str = ...

# ─── Error ────────────────────────────────────────────────────────────────────

class Warning(Exception): ...
class Error(Exception): ...
class InterfaceError(Error): ...
class DatabaseError(Error): ...
class DataError(DatabaseError): ...
class OperationalError(DatabaseError): ...
class IntegrityError(DatabaseError): ...
class InternalError(DatabaseError): ...
class ProgrammingError(DatabaseError): ...
class NotSupportedError(DatabaseError): ...

# ─── Connection ───────────────────────────────────────────────────────────────

class Connection(pep249.Connection):
    def ping(): ...

class Cursor(pep249.Cursor): ...

# ─── Type Constructor ─────────────────────────────────────────────────────────

def Date(year: int, month: int, day: int) -> datetime.date: ...

# ─── Sqlalchemy Compatibility ─────────────────────────────────────────────────

def __getattr__(self, attr: str) -> Any: ...
