# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DeploymentState(str, Enum):
    """
    Deployment status
    """

    """
    allowed enum values
    """
    NOT_STARTED = 'NOT_STARTED'
    DEPLOYING = 'DEPLOYING'
    DEPLOYED = 'DEPLOYED'
    DEPROVISIONED = 'DEPROVISIONED'
    DEPROVISIONING = 'DEPROVISIONING'
    FAILED = 'FAILED'
    PENDING = 'PENDING'
    PROVISIONED = 'PROVISIONED'
    PROVISIONING = 'PROVISIONING'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DeploymentState from a JSON string"""
        return cls(json.loads(json_str))


