# coding: utf-8

"""
    py4heappe API

    Merged API documentation for py4heappe client  # noqa: E501

    OpenAPI spec version: v5.0.0
    Contact: support.heappe@it4i.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py4heappe.heappe_v5.core.configuration import Configuration


class CreateCommandTemplateFromGenericModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_code': 'str',
        'generic_command_template_id': 'int',
        'name': 'str',
        'project_id': 'int',
        'description': 'str',
        'extended_allocation_command': 'str',
        'executable_file': 'str',
        'preparation_script': 'str'
    }

    attribute_map = {
        'session_code': 'SessionCode',
        'generic_command_template_id': 'GenericCommandTemplateId',
        'name': 'Name',
        'project_id': 'ProjectId',
        'description': 'Description',
        'extended_allocation_command': 'ExtendedAllocationCommand',
        'executable_file': 'ExecutableFile',
        'preparation_script': 'PreparationScript'
    }

    def __init__(self, session_code=None, generic_command_template_id=None, name=None, project_id=None, description=None, extended_allocation_command=None, executable_file=None, preparation_script=None, _configuration=None):  # noqa: E501
        """CreateCommandTemplateFromGenericModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._session_code = None
        self._generic_command_template_id = None
        self._name = None
        self._project_id = None
        self._description = None
        self._extended_allocation_command = None
        self._executable_file = None
        self._preparation_script = None
        self.discriminator = None

        if session_code is not None:
            self.session_code = session_code
        if generic_command_template_id is not None:
            self.generic_command_template_id = generic_command_template_id
        if name is not None:
            self.name = name
        if project_id is not None:
            self.project_id = project_id
        if description is not None:
            self.description = description
        if extended_allocation_command is not None:
            self.extended_allocation_command = extended_allocation_command
        if executable_file is not None:
            self.executable_file = executable_file
        if preparation_script is not None:
            self.preparation_script = preparation_script

    @property
    def session_code(self):
        """Gets the session_code of this CreateCommandTemplateFromGenericModel.  # noqa: E501

        Session code  # noqa: E501

        :return: The session_code of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :rtype: str
        """
        return self._session_code

    @session_code.setter
    def session_code(self, session_code):
        """Sets the session_code of this CreateCommandTemplateFromGenericModel.

        Session code  # noqa: E501

        :param session_code: The session_code of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                session_code is not None and len(session_code) > 50):
            raise ValueError("Invalid value for `session_code`, length must be less than or equal to `50`")  # noqa: E501
        if (self._configuration.client_side_validation and
                session_code is not None and len(session_code) < 0):
            raise ValueError("Invalid value for `session_code`, length must be greater than or equal to `0`")  # noqa: E501

        self._session_code = session_code

    @property
    def generic_command_template_id(self):
        """Gets the generic_command_template_id of this CreateCommandTemplateFromGenericModel.  # noqa: E501

        Generic command template id  # noqa: E501

        :return: The generic_command_template_id of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :rtype: int
        """
        return self._generic_command_template_id

    @generic_command_template_id.setter
    def generic_command_template_id(self, generic_command_template_id):
        """Sets the generic_command_template_id of this CreateCommandTemplateFromGenericModel.

        Generic command template id  # noqa: E501

        :param generic_command_template_id: The generic_command_template_id of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :type: int
        """

        self._generic_command_template_id = generic_command_template_id

    @property
    def name(self):
        """Gets the name of this CreateCommandTemplateFromGenericModel.  # noqa: E501

        Name  # noqa: E501

        :return: The name of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateCommandTemplateFromGenericModel.

        Name  # noqa: E501

        :param name: The name of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                name is not None and len(name) > 80):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `80`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name is not None and len(name) < 0):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `0`")  # noqa: E501

        self._name = name

    @property
    def project_id(self):
        """Gets the project_id of this CreateCommandTemplateFromGenericModel.  # noqa: E501

        Project id  # noqa: E501

        :return: The project_id of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this CreateCommandTemplateFromGenericModel.

        Project id  # noqa: E501

        :param project_id: The project_id of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :type: int
        """

        self._project_id = project_id

    @property
    def description(self):
        """Gets the description of this CreateCommandTemplateFromGenericModel.  # noqa: E501

        Description  # noqa: E501

        :return: The description of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateCommandTemplateFromGenericModel.

        Description  # noqa: E501

        :param description: The description of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                description is not None and len(description) > 200):
            raise ValueError("Invalid value for `description`, length must be less than or equal to `200`")  # noqa: E501
        if (self._configuration.client_side_validation and
                description is not None and len(description) < 0):
            raise ValueError("Invalid value for `description`, length must be greater than or equal to `0`")  # noqa: E501

        self._description = description

    @property
    def extended_allocation_command(self):
        """Gets the extended_allocation_command of this CreateCommandTemplateFromGenericModel.  # noqa: E501

        Extended allocation command  # noqa: E501

        :return: The extended_allocation_command of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :rtype: str
        """
        return self._extended_allocation_command

    @extended_allocation_command.setter
    def extended_allocation_command(self, extended_allocation_command):
        """Sets the extended_allocation_command of this CreateCommandTemplateFromGenericModel.

        Extended allocation command  # noqa: E501

        :param extended_allocation_command: The extended_allocation_command of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                extended_allocation_command is not None and len(extended_allocation_command) > 100):
            raise ValueError("Invalid value for `extended_allocation_command`, length must be less than or equal to `100`")  # noqa: E501
        if (self._configuration.client_side_validation and
                extended_allocation_command is not None and len(extended_allocation_command) < 0):
            raise ValueError("Invalid value for `extended_allocation_command`, length must be greater than or equal to `0`")  # noqa: E501

        self._extended_allocation_command = extended_allocation_command

    @property
    def executable_file(self):
        """Gets the executable_file of this CreateCommandTemplateFromGenericModel.  # noqa: E501

        Executable file  # noqa: E501

        :return: The executable_file of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :rtype: str
        """
        return self._executable_file

    @executable_file.setter
    def executable_file(self, executable_file):
        """Sets the executable_file of this CreateCommandTemplateFromGenericModel.

        Executable file  # noqa: E501

        :param executable_file: The executable_file of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                executable_file is not None and len(executable_file) > 255):
            raise ValueError("Invalid value for `executable_file`, length must be less than or equal to `255`")  # noqa: E501
        if (self._configuration.client_side_validation and
                executable_file is not None and len(executable_file) < 0):
            raise ValueError("Invalid value for `executable_file`, length must be greater than or equal to `0`")  # noqa: E501

        self._executable_file = executable_file

    @property
    def preparation_script(self):
        """Gets the preparation_script of this CreateCommandTemplateFromGenericModel.  # noqa: E501

        Preparation script  # noqa: E501

        :return: The preparation_script of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :rtype: str
        """
        return self._preparation_script

    @preparation_script.setter
    def preparation_script(self, preparation_script):
        """Sets the preparation_script of this CreateCommandTemplateFromGenericModel.

        Preparation script  # noqa: E501

        :param preparation_script: The preparation_script of this CreateCommandTemplateFromGenericModel.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                preparation_script is not None and len(preparation_script) > 500):
            raise ValueError("Invalid value for `preparation_script`, length must be less than or equal to `500`")  # noqa: E501
        if (self._configuration.client_side_validation and
                preparation_script is not None and len(preparation_script) < 0):
            raise ValueError("Invalid value for `preparation_script`, length must be greater than or equal to `0`")  # noqa: E501

        self._preparation_script = preparation_script

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateCommandTemplateFromGenericModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateCommandTemplateFromGenericModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateCommandTemplateFromGenericModel):
            return True

        return self.to_dict() != other.to_dict()
