import os

def getDefaultCachePath() -> os.PathLike: ...
def getDefaultModelsPath() -> os.PathLike: ...
def getDownloadEndpoint() -> str: ...
def getHealthEndpoint() -> str: ...
def setDefaultCachePath(path: os.PathLike) -> None: ...
def setDefaultModelsPath(path: os.PathLike) -> None: ...
def setDownloadEndpoint(endpoint: str) -> None: ...
def setHealthEndpoint(endpoint: str) -> None: ...
