# coding: utf-8

"""
    Metal API

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.metalv1.api.console_log_details_api import ConsoleLogDetailsApi


class TestConsoleLogDetailsApi(unittest.TestCase):
    """ConsoleLogDetailsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConsoleLogDetailsApi()

    def tearDown(self) -> None:
        pass

    def test_capture_screenshot(self) -> None:
        """Test case for capture_screenshot

        """
        pass


if __name__ == '__main__':
    unittest.main()
