# coding: utf-8

# flake8: noqa
"""
    PhrameAPI

    Phrame API

    The version of the OpenAPI document: 1.0.4
    Contact: david@3adesign.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from PhrameAPI.models.db_phrame_json_store import DbPhrameJSONStore
from PhrameAPI.models.db_phrame_ui_configuration import DbPhrameUIConfiguration
