# coding: utf-8

"""
    Metal API

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.metalv1.models.request_ip_reservation_request import RequestIPReservationRequest

class TestRequestIPReservationRequest(unittest.TestCase):
    """RequestIPReservationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestIPReservationRequest:
        """Test RequestIPReservationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestIPReservationRequest`
        """
        model = RequestIPReservationRequest()
        if include_optional:
            return RequestIPReservationRequest(
                comments = '',
                customdata = equinix.services.metalv1.models.customdata.customdata(),
                details = '',
                facility = '',
                fail_on_approval_required = True,
                href = '',
                metro = 'SV',
                quantity = 56,
                tags = [
                    ''
                    ],
                type = 'vrf',
                cidr = 22,
                network = '10.1.2.0',
                vrf_id = ''
            )
        else:
            return RequestIPReservationRequest(
                quantity = 56,
                type = 'vrf',
                cidr = 22,
                network = '10.1.2.0',
                vrf_id = '',
        )
        """

    def testRequestIPReservationRequest(self):
        """Test RequestIPReservationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
