from kilojoule.templates.SI import *

T.set_units("degR")
p.set_units("psi")
v.set_units("ft^3/lb")
u.set_units("Btu/lb")
h.set_units("Btu/lb")
s.set_units("Btu/lb/degR")
m.set_units("lb")
Vol.set_units("ft^3")
Vel.set_units("ft/s")
X.set_units("Btu")
Xdot.set_units("hp")
phi.set_units("Btu/lb")
psi.set_units("Btu/lb")
