from .spod_endpoints import (
    AUTHENTICATION_PATH,
    ARTICLES_PATH,
    ORDERS_PATH,
    ORDER_SIMULATE_CANCELLED_EVENT_PATH,
    ORDER_SIMULATE_PROCESSED_EVENT_PATH,
    ORDER_SIMULATE_SHIPMENT_SENT_EVENT_PATH,
    SUBSCRIPTIONS_PATH,
    PRODUCT_TYPES_PATH,
    STOCKS_PATH,
    DESIGNS_PATH,
)
