from __future__ import annotations

import buttonpad

puzzles = """THE GEMS ARE NOT IN THE WHITE BOX.,THE GEMS ARE NOT IN THIS BOX.,THE GEMS ARE IN THIS BOX.,BLUE
THE GEMS ARE ON THE DESK.,THE GEMS ARE IN THIS BOX.,THE GEMS ARE ON THE FLOOR.,WHITE
YOU ARE IN THE PARLOR.,THIS BOX IS EMPTY.,THE BLUE BOX IS TRUE.,WHITE
ONLY ONE BOX IS TRUE.,ONLY ONE BOX CONTAINS GEMS.,THE GEMS ARE IN THE WHITE BOX.,WHITE
THIS BOX AND THE WHITE BOX ARE BOTH EMPTY.,THIS BOX AND THE BLUE BOX ARE BOTH EMPTY.,THE OTHER TWO STATEMENTS HAVE IDENTICAL WORDING.,BLACK
THE GEMS ARE IN A BOX WITH A STATEMENT.,[NOTHING],THE WHITE BOX DOES NOT HAVE A STATEMENT.,WHITE
THE GEMS ARE IN THE BLACK BOX.,[NOTHING],THE GEMS ARE IN A BOX WITH A STATEMENT.,BLUE
GEMS ARE IN BOTH THE BLACK BOX AND THE WHITE BOX.,GEMS ARE IN BOTH THE BLUE BOX AND THE BLACK BOX.,GEMS ARE NOT IN THE WHITE BOX OR THE BLUE BOX.,BLACK
THE GEMS ARE IN THE WHITE BOX.,"STATEMENTS WITH THE WORD ""WHITE"" ARE ALWAYS TRUE.",THE STATEMENT ON THE WHITE BOX IS TRUE.,WHITE
"THE GEMS ARE IN A BOX WITH A STATEMENT CONTAINING 
THE LETTER ""B"".",THE BLUE BOX IS TRUE.,"THE GEMS ARE IN A BOX WITH A STATEMENT CONTAINING 
THE LETTER ""U"".",BLUE
THE OTHER TWO BOXES ARE TRUE.,THE OTHER TWO BOXES ARE BLUE.,THE OTHER TWO BOXES ARE EMPTY.,BLACK
ONLY ONE BOX IS TRUE.,THE BLACK BOX CONTAINS THE GEMS.,THE BLUE BOX CONTAINS THE GEMS.,WHITE
THIS BOX IS NOT EMPTY.,THIS BOX CONTAINS THE GEMS.,"ALL STATEMENTS THAT CONTAIN THE WORD 'GEMS' ARE 
FALSE.",WHITE
THE GEMS ARE NOT IN THIS BOX.,THE BLUE BOX IS TRUE.,THE GEMS ARE IN THIS BOX.,WHITE
THIS IS THE ONLY TRUE BOX.,THE GEMS ARE IN THE OTHER BOX WITH A TRUE STATEMENT.,ONE OF THE OTHER BOXES IS TRUE.,BLACK
THE GEMS ARE IN THE WHITE BOX.,THE OTHER TWO STATEMENTS ARE BOTH TRUE.,THE GEMS ARE NOT IN THE BLUE BOX.,BLACK
THE BOX NEXT TO THIS BOX IS FALSE.,A BOX NEXT TO THIS BOX IS TRUE.,THE BOX NEXT TO THIS BOX CONTAINS GEMS.,WHITE
THERE ARE TWO FALSE STATEMENTS.,THIS IS THE ONLY TRUE STATEMENT.,THE WHITE BOX IS EMPTY.,WHITE
THIS BOX IS NOT BLUE.,EVERY STATEMENT WITH THE WORD BLUE IS FALSE.,THE BLACK BOX AND BLUE BOX ARE EMPTY.,WHITE
A BOX NEXT TO THIS BOX CONTAINS GEMS.,[NOTHING],A BOX NEXT TO THIS BOX DISPLAYS A FALSE STATEMENT.,WHITE
THE GEMS ARE IN THE BLACK BOX.,THE GEMS ARE IN THE WHITE BOX.,ONLY ONE BOX DISPLAYS A TRUE STATEMENT.,BLUE
THE BLACK BOX IS NOT EMPTY.,THE STATEMENT ON THE BLACK BOX IS TRUE.,A BOX WITH A FALSE STATEMENT CONTAINS THE GEMS.,BLUE
THE GEMS ARE IN THE WHITE BOX.,A BOX WITH A FALSE STATEMENT CONTAINS THE GEMS.,THE STATEMENT ON THE WHITE BOX IS TRUE.,BLUE
THIS BOX CONTAINS THE GEMS.,THIS BOX DOES NOT CONTAIN THE GEMS.,THE OTHER TWO BOXES ARE TRUE.,BLACK
THE TRUE BOXES ARE BOTH EMPTY.,THE FALSE BOXES ARE BOTH TRUE.,THE GEMS ARE IN THE BLUE BOX.,BLUE
THE GEMS ARE NOT IN A BOX WITH A TRUE STATEMENT.,"THE STATEMENT ON THE BLUE BOX IS AS TRUE AS THIS 
STATEMENT.",THE GEMS ARE NOT IN A BOX WITH A TRUE STATEMENT.,WHITE
ONLY ONE STATEMENT IS FALSE.,ONLY ONE STATEMENT IS TRUE.,THE GEMS ARE IN A BOX WITH A FALSE STATEMENT.,WHITE
"THE LETTER 'B' APPEARS TWICE ON THE BOX THAT 
CONTAINS THE GEMS.",ALL STATEMENTS THAT CONTAIN MORE THAN ONE 'B' ARE TRUE.,THE BLUE BOX CONTAINS THE GEMS.,BLACK
YOU WILL OPEN THIS BOX AND FIND IT EMPTY.,A TRUE BOX CONTAINS THE GEMS.,THIS BOX AND THE WHITE BOX ARE BOTH FALSE.,WHITE
"THERE ARE TWO STATEMENTS ON THIS BOX. 

THEY ARE BOTH FALSE.","THERE ARE TWO STATEMENTS ON THIS BOX. 

THE GEMS ARE IN A BOX WITH NO TRUE STATEMENTS.",THERE ARE TWO STATEMENTS ON THIS BOX.,BLACK
YOU WILL NOT SOLVE THIS PUZZLE.,"FOUR STATEMENTS ON BOXES IN THIS ROOM ARE TRUE. 

A BOX WITH ONE FALSE STATEMENT CONTAINS GEMS.","A BOX WITH A TRUE STATEMENT CONTAINS THE GEMS. 

THIS BOX DOES NOT CONTAIN THE GEMS.",WHITE
"THE WHITE BOX HAS A TRUE STATEMENT. 

THE BLACK BOX HAS A TRUE STATEMENT.","THE BLACK BOX HAS A FALSE STATEMENT. 

THE GEMS ARE IN THE BOX WITH TWO FALSE STATEMENTS.","THE BLUE BOX HAS TWO FALSE STATEMENTS. 

THE BOX WITH TWO TRUE STATEMENTS HAS THE GEMS.",BLACK
"BOTH OF THESE STATEMENTS ARE TRUE. 

THE GEMS ARE IN THIS BOX.","THE GEMS ARE NOT IN THE BLUE BOX. 

THE GEMS ARE NOT IN THE BLACK BOX.","THE GEMS ARE IN A BOX WITH A FALSE STATEMENT. 

BOTH STATEMENTS ON THE BLUE BOX ARE TRUE.",WHITE
THE BLACK BOX IS TRUE AND IT CONTAINS THE GEMS.,THE BLACK BOX IS FALSE. THE ABOVE STATEMENT IS FALSE.,THE BLUE BOX IS EMPTY IF IT IS FALSE.,WHITE
"A STATEMENT WITH AN ODD NUMBER OF WORDS IS ALWAYS 
TRUE. 

THE GEMS ARE IN THE BOX WITH THE MOST WORDS.","FALSE STATEMENTS HAVE LESS THAN SIX WORDS. 

THAT'S NOT TRUE.",THIS BOX HAS GEMS.,BLACK
"TWO OF THE TOP STATEMENTS ARE FALSE

ONLY ONE BOTTOM STATEMENT IS FALSE","THE GEMS ARE IN A BOX WITH A TRUE TOP STATEMENT

THE GEMS ARE IN A BOX WITH A FALSE BOTTOM STATEMENT","TWO OF THE TOP STATEMENTS ARE TRUE

ONLY ONE BOTTOM STATEMENT IS TRUE",BLACK
"STATEMENTS CONTAINING THE WORD 'STATEMENTS' 
ARE ALWAYS TRUE.",BOTH STATEMENTS ON THE BLACK BOX ARE FALSE.,"THE GEMS ARE IN THE BOX WITH A TRUE STATEMENT. 

THIS IS THE SECOND STATEMENT ON THIS BOX.",BLACK
"ONLY ONE BOX NEXT TO THIS BOX IS FALSE AND IT 
CONTAINS GEMS.","ONLY ONE BOX NEXT TO THIS BOX IS FALSE AND IT 
CONTAINS GEMS.","ONLY ONE BOX NEXT TO THIS BOX IS FALSE AND IT 
CONTAINS GEMS.",WHITE
"THE GEMS ARE IN A BOX WITH TWO STATEMENTS. 

THAT IS TRUE.",THE GEMS ARE IN THE BLUE BOX.,"THE BLUE BOX HAS AT LEAST ONE TRUE STATEMENT. 

THE WHITE BOX HAS AT LEAST ONE TRUE STATEMENT.",BLACK
"THE STATEMENTS ON THIS BOX ARE EITHER BOTH 
TRUE OR BOTH FALSE. 

THIS BOX IS EMPTY.",THIS BOX IS WHITE.,"ALL STATEMENTS ON THE BLUE BOX ARE TRUE. 

THE BOX WITH NO FALSE STATEMENTS HAS THE GEMS.",BLACK
THE EMPTY BOXES ARE BOTH TRUE.,THE EMPTY BOXES ARE BOTH FALSE.,THIS IS NOT AN EMPTY BOX.,WHITE
THIS BOX'S STATEMENT IS BOTH TRUE AND FALSE.,THE BLUE BOX CONTAINS THE GEMS IF ITS STATEMENT IS FALSE.,"THIS STATEMENT IS AS TRUE AS THE WHITE BOX'S 
STATEMENT.",BLUE
THE GEMS ARE NOT IN THE BLACK BOX.,"THIS STATEMENT IS AS TRUE AS THE STATEMENT ON THE 
BLACK BOX.",THE GEMS ARE IN THE WHITE BOX.,WHITE
A BOX THAT DISPLAYS THE WORD 'TRUE' IS FALSE.,A BOX THAT DISPLAYS THE WORD 'GEMS' IS EMPTY.,THE WHITE BOX IS TRUE AND DOES NOT CONTAIN GEMS.,WHITE
"THE SECOND STATEMENT ON THE BLACK BOX IS FALSE. 

THE BLACK BOX CONTAINS THE GEMS.",EVERY STATEMENT WITH THE WORD 'BLUE' IS FALSE.,"BOTH STATEMENTS ON THE BLUE BOX ARE TRUE. 

THE BLUE BOX CONTAINS GEMS.",BLACK
"THIS IS NOT AN EMPTY BOX. 

THE GEMS ARE NOT IN THE BLACK BOX.","THIS STATEMENT IS TRUE. 

THE ABOVE STATEMENT IS FALSE.","THE GEMS ARE IN THE BLACK BOX. 

THE GEMS ARE IN THE WHITE  BOX.",BLUE
"THE GEMS ARE IN A BOX WITH THE LONGEST WORD. 

""LONGEST"" IS THE LONGEST WORD ON A BOX.","THE GEMS ARE IN A BOX WITH THE SHORTEST WORD. 

""A"" IS THE SHORTEST WORD ON A BOX.","THERE ARE WORD ON THE BOX WITH THE GEMS. 

THIS BOX DOES NOT CONTAIN THE GEMS.",BLUE
THERE IS ONLY ONE TRUE BOX.,BOTH STATEMENTS WRITTEN ON THE OTHER BOXES ARE FALSE.,THE BOX WITH THE MOST WORDS DOES NOT HAVE GEMS.,BLACK
"THE GEMS ARE IN THIS BOX. 

THE ABOVE STATEMENT IS TRUE.","THE GEMS ARE NOT IN THIS BOX. 

THE ABOVE STATEMENT IS FALSE.","THE TOP STATEMENT OF EACH BOX IS TRUE. 

THE ABOVE STATEMENT IS TRUE.",BLUE
"THE WHITE BOX HAS EXACTLY ONE TRUE STATEMENT. 

THE BLACK BOX HAS NO TRUE STATEMENTS.","THE GEMS ARE NOT IN THE BLACK BOX. 

THE ABOVE STATEMENTS IS TRUE.","THE BLUE BOX HAS EXACTLY ONE TRUE STATEMENT. 

THE GEMS ARE IN THE BLUE BOX.",BLUE
THIS BOX IS EMPTY.,"THIS BOX IS EMPTY. 

THE BLUE BOX IS EMPTY.","THIS BOX IS EMPTY. 

EVERY STATEMENT WITH THE WORD EMPTY IS FALSE.",BLACK
"THE GEMS ARE NOT IN THIS BOX. 

THE GEMS ARE NOT IN THE WHITE BOX.","THE GEMS ARE NOT IN THIS BOX. 

THE GEMS ARE IN THE BLUE BOX.","THE GEMS ARE NOT IN THIS BOX. 

THE GEMS ARE IN THE BLUE BOX.",BLACK
THE WHITE BOX IS EMPTY.,THE BLUE BOX IS FALSE.,THE EMPTY BOXES BOTH HAVE FALSE STATEMENTS.,BLACK
"THE TOP STATEMENT ON THE WHITE BOX IS TRUE. 

THE GEMS ARE NOT IN THIS BOX.","EXACTLY TWO STATEMENTS WITH THE WORD 'TRUE' ARE FALSE. 

THE GEMS ARE NOT IN THIS BOX.","BOTH STATEMENTS ON THE WHITE BOX ARE TRUE. 

BOTH STATEMENTS ON THIS BOX ARE TRUE.",WHITE 
"ONLY ONE OF THE STATEMENTS ON THIS BOX ARE [sic] 
FALSE. 

THE GEMS ARE IN THE WHITE BOX.","ONLY ONE OF THE STATEMENTS ON THIS BOX ARE [sic] TRUE. 

THE GEMS ARE IN A BOX WITH A TRUE STATEMENT.","THERE ARE THREE FALSE STATEMENTS ON BOXES IN THIS 
ROOM.",BLUE 
THE GEMS ARE NOT IN THE BLACK BOX.,THE GEMS ARE IN THE BLUE BOX.,"BOTH OF THESE STATEMENTS ARE FALSE. 

THE STATEMENT ON THE WHITE BOX IS FALSE.",WHITE
ONLY ONE STATEMENT IS TRUE.,A BOX NEXT TO THIS BOX IS TRUE.,A BOX NEXT TO THIS BOX CONTAINS GEMS.,WHITE
"ONLY ONE OF THIS BOX'S STATEMENTS IS TRUE. 

THE GEMS ARE IN A BOX WITH A TRUE STATEMENT. 

THE GEMS ARE IN A BOX WITH TWO STATEMENTS.","THE GEMS ARE IN A BOX WITH A FALSE STATEMENT. 

THE GEMS ARE IN A BOX NEXT TO THIS BOX.","ONLY ONE OF THIS BOX'S STATEMENTS ARE [sic] FALSE. 

THE GEMS ARE IN A BOX WITH THREE STATEMENTS. 

THERE ARE THE SAME NUMBER OF TRUE AND FALSE 
STATEMENTS ON BOXES.",BLUE
"THIS BOX HAS NO FALSE STATEMENTS. 

THE GEMS ARE IN A BOX WITH A SIX WORD STATEMENT. 

THIS STATEMENT CONTAINS SIX WORDS.","THE GEMS ARE IN A BOX WITH A STATEMENT CONTAINING 
THE WORD ""SIX"". 

THERE IS A BOX THAT CONTAINS A MIX OF TRUE AND 
FALSE STATEMENTS. 

THIS STATEMENT CONTAINS FIVE WORDS.","THE BLUE BOX CONTAINS EXACTLY ONE FALSE STATEMENT. 

THE GEMS ARE IN A BOX WITH A FIVE WORD STATEMENT. 

THIS HAS NO TRUE STATEMENTS.",WHITE
"ALL BOXES DISPLAYING THE WORD ""EMPTY"" ARE EMPTY. 

ALL BOXES DISPLAYING THE WORD ""TRUE"" ARE TRUE.","ALL BOXES DISPLAYING THE WORD ""GEMS"" CONTAIN GEMS. 

ALL STATEMENTS DISPLAYING THE WORD ""WORD"" CONTAIN 
WORDS.","ALL STATEMENTS DISPLAYING THE WORD ""BOXES"" ARE FALSE. 

ALL STATEMENTS DISPLAYING THE WORD ""STATEMENTS"" 
ARE TRUE.",WHITE
"A BOX WITH A TRUE STATEMENT IS EMPTY. 

A BOX WITH A FALSE STATEMENT IS EMPTY. 

THE WHITE BOX IS EMPTY.","A BOX WITH ONLY TRUE STATEMENTS IS EMPTY. 

THE BLACK BOX IS EMPTY. 

A BOX WITH A STATEMENT THAT IS ALSO ON ANOTHER BOX IS 
EMPTY.","A BOX WITH MORE THAN ONE FALSE STATEMENT IS EMPTY. 

THE BLACK BOX IS EMPTY.  

A BOX WITH NO TRUE STATEMENTS IS EMPTY.",BLACK
"THIS BOX HAS AT LEAST TWO TRUE STATEMENTS. 

THE BLACK BOX HAS AT LEAST TWO TRUE STATEMENTS. 

THE GEMS ARE IN THIS BOX.","EVERY STATEMENT ON THE BLUE BOX IS FALSE. 

EVERY STATEMENT ON THE BLACK BOX IS TRUE. 

THE GEMS ARE IN THIS BOX.","THIS IS A TRUE STATEMENT. 

THIS IS A TRUE STATEMENT. 

THE GEMS ARE IN THIS BOX.",BLUE
"THE STATEMENT MATCHING THIS STATEMENT IS TRUE. 

THE STATEMENT MATCHING THIS STATEMENT IS ON A 
COMPLETELY TRUE BOX.","THE STATEMENT MATCHING THIS STATEMENT IS TRUE. 

THE STATEMENT MATCHING THIS STATEMENT IS ON A BOX 
CONTAINING GEMS.","THE STATEMENT MATCHING THIS STATEMENT IS ON A BOX 
CONTAINING GEMS. 

THE STATEMENT MATCHING THIS STATEMENT IS ON A 
COMPLETELY TRUE BOX.",BLACK
"THE STATEMENT MATCHING THIS STATEMENT IS ON 
AN EMPTY BOX. 

THE GEMS ARE IN A BOX WITH A FALSE STATEMENT. 

THERE IS AT LEAST ONE TRUE STATEMENT ON THIS BOX.","THE GEMS ARE IN A BOX WITH A TRUE STATEMENT. 

THE GEMS ARE IN A BOX WITH A FALSE STATEMENT. ","THE STATEMENT MATCHING THIS STATEMENT IS ON 
AN EMPTY BOX. 

THE GEMS ARE IN A BOX WITH THREE STATEMENTS. 

THERE ARE AN EQUAL NUMBER OF TRUE AND FALSE 
STATEMENTS.",BLACK
"ONLY ONE OF WHITE BOX'S STATEMENTS IS TRUE. 

THE BLACK BOX CONTAINS THE GEMS. 

THE BLUE BOX IS EMPTY.","ONLY ONE OF BLUE BOX'S STATEMENTS IS TRUE. 

THE BLACK BOX IS EMPTY. 

THE GEMS ARE IN A BOX WITH A TRUE STATEMENT.","ONLY ONE OF THIS BOX'S STATEMENTS IS TRUE. 

THE BLUE BOX CONTAINS THE GEMS. 

THE WHITE BOX IS EMPTY.",WHITE
"A BOX WITH A TRUE STATEMENT CONTAINS THE GEMS. 

A BOX WITH A FALSE STATEMENT CONTAINS THE GEMS. 

A BOX MENTIONING THE WORD ""TRUE"" CONTAINS THE GEMS.","A BOX WITH ONLY TRUE STATEMENTS CONTAINS THE GEMS. 

THE BLUE BOX CONTAINS THE GEMS. 

A BOX WITH A STATEMENT THAT IS ALSO ON ANOTHER BOX 
CONTAINS THE GEMS.","A BOX WITH A FALSE STATEMENT CONTAINS THE GEMS. 

THE WHITE BOX CONTAINS THE GEMS. 

A BOX MENTIONING A SPECIFIC COLOR CONTAINS THE GEMS.",WHITE
"THERE IS NO BOX THAT CONTAINS A MIX OF TRUE AND 
FALSE STATEMENTS. 

THERE IS NO BOX THAT DISPLAYS 3 FALSE STATEMENTS. 

THERE IS NO BOX THAT DISPLAYS A NUMBER THAT ALSO 
APPEARS ON ANOTHER BOX.","THERE IS NO BOX THAT MENTIONS A SPECIFIC COLOR. 

THERE IS NO BOX THAT DISPLAYS 3 TRUE STATEMENTS.","THERE IS NO BOX IN BETWEEN 2 EMPTY BOXES. 

THERE IS NO BOX THAT CONTAINS A STATEMENT WITH LESS 
THAN 8 WORDS. 

THERE IS NO BOX THAT DISPLAYS EXACTLY 1 TRUE 
STATEMENT.",WHITE
THE GEMS ARE IN THIS BOX.,THIS STATEMENT IS OF NO HELP AT ALL.,THE GEMS ARE IN THE BLUE BOX.,BLUE
THE GEMS ARE IN THE ONLY BOX WITH A TRUE STATEMENT.,ONE OF THE OTHER BOXES IS TRUE.,THE GEMS ARE IN THE ONLY BOX WITH A FALSE STATEMENT.,BLUE
THE GEMS ARE IN THIS BOX.,THE GEMS ARE IN A BOX NEXT TO THIS BOX.,THE GEMS ARE IN THE BLUE BOX.,BLACK
THE EMPTY BOXES BOTH HAVE TRUE STATEMENTS.,THE BLUE BOX HAS A TRUE STATEMENT.,THIS BOX CONTAINS GEMS.,BLACK
THERE IS ONLY ONE TRUE STATEMENT.,THE GEMS ARE IN A BOX WITH A FALSE STATEMENT.,THERE ARE TWO TRUE STATEMENTS.,BLUE
THE GEMS ARE IN THE BLACK BOX.,THE GEMS ARE NOT IN THIS BOX.,THE STATEMENTS ON THIS OTHER TWO BOXES ARE TRUE.,BLUE
THE EMPTY BOXES ARE BOTH TRUE.,THE GEMS ARE IN THE BLACK BOX.,THIS IS NOT AN EMPTY BOX.,BLACK
THE BLACK BOX IS FALSE.,THE BLACK BOX IS TRUE.,A FALSE BOX CONTAINS THE GEMS.,BLUE
A BOX WITH A FALSE STATEMENT CONTAINS THE GEMS.,THE STATEMENT ON THE BLUE BOX IS TRUE.,THE BLUE BOX CONTAINS THE GEMS.,BLACK
THE GEMS ARE IN ANOTHER BOX.,THE TRUTH IS ON ANOTHER BOX.,THE WORDS 'ANOTHER BOX' ARE ON ANOTHER BOX.,BLUE
THERE ARE TWO TRUE BOXES.,THERE ARE TWO EMPTY BOXES.,THIS BOX IS EMPTY.,BLACK
THE GEMS ARE IN THE BLACK BOX.,EVERY STATEMENT WITH THE WORD BLACK IS FALSE.,THE GEMS ARE IN THE BLUE BOX.,BLACK
THE GEMS ARE IN THE BLACK BOX.,THIS STATEMENT IS OF NO HELP AT ALL.,THIS BOX AND THE BLUE BOX ARE BOTH FALSE.,BLACK
THE GEMS ARE IN A BOX WITH A FALSE STATEMENT.,THE BLUE BOX IS FALSE.,THE WHITE BOX IS FALSE.,WHITE
THE GEMS ARE ON THE TABLE BEHIND YOU.,THE GEMS ARE IN THIS BOX.,EVERY STATEMENT CLAIMING WHERE THE GEMS ARE IS FALSE. THE GEMS ARE IN THE BLUE BOX.,WHITE
THIS BOX IS EMPTY.,A BOX WITH A FALSE STATEMENT IS EMPTY.,THERE ARE TWO FALSE STATEMENTS.,WHITE
THE GEMS ARE NOT IN THIS BOX.,THE GEMS ARE IN THIS BOX.,THE WHITE BOX IS TRUE.,BLACK
ONE OF THE OTHER TWO BOXES IS FALSE.,YOU WILL OPEN THIS BOX AND FIND IT EMPTY.,THE BLUE BOX IS TRUE.,WHITE
THE GEMS ARE IN THE ONLY TRUE BOX.,ONLY ONE STATEMENT IS TRUE.,THE GEMS ARE IN THE BLUE BOX.,BLACK
BOXES NEXT TO THIS BOX CONTAINS GEMS.,BOXES NEXT TO THIS BOX CONTAINS GEMS.,BOXES NEXT TO THIS BOX CONTAINS GEMS.,WHITE
THE WHITE BOX IS TRUE.,THE OTHER TWO BOXES ARE FALSE.,THE OTHER TWO BOXES ARE EMPTY.,BLACK
THIS BOX IS EMPTY.,THIS BOX IS EMPTY.,THIS PUZZLE IS HARDER THAN IT SEEMS.,BLACK
THE BLACK BOX IS TRUE.,THE GEMS ARE IN THE TRUE BOX.,THE BLUE BOX IS TRUE.,WHITE
TWO OF THESE STATEMENTS ARE TRUE.,THE STATEMENT ON THE BLUE BOX IS TRUE.,THE GEMS ARE IN A BOX WITH A TRUE STATEMENT.,BLACK
ALL THREE STATEMENTS ARE FALSE.,TWO STATEMENTS ARE FALSE.,THE GEMS ARE IN A BOX WITH A FALSE STATEMENT.,WHITE
EVERY BOX IS BLACK.,EVERY BOX CONTAINS GEMS.,"THE STATEMENT ON ONE OF THE OTHER TWO BOXES WOULD 
BE TRUE IF YOU REPLACED THE WORD 'EVERY' WITH THE 
WORD 'THIS'",WHITE
THE BLACK BOX IS BLACK.,THE BLACK BOX IS TRUE.,THE BLACK BOX IS EMPTY.,BLACK
THE GEMS ARE IN THE FALSE BOX. ,THE GEMS ARE IN THE FALSE BOX. ,ONLY ONE OF THE OTHER BOXES IS FALSE.,BLACK
"THE GEMS ARE IN A BOX WITH THE WORD ""BLUE"" ON IT.",[NOTHING],THE GEMS ARE IN A BOX THAT IS ACTUALLY BLUE.,BLACK
A BOX NEXT TO THIS BOX CONTAINS GEMS.,BOTH BOXES NEXT TO THIS BOX CONTAIN GEMS.,A BOX NEXT TO THIS BOX IS TRUE.,WHITE
THE STATEMENT ON THE WHITE BOX IS TRUE.,THERE IS A SECOND WIND-UP KEY IN THIS ROOM.,THE BOX AND THE WHITE BOX ARE BOTH EMPTY.,BLUE
THIS BOX IS THE WHITE BOX.,THIS BOX IS THE BLACK BOX.,THE BLUE BOX CONTAINS THE GEMS.,BLUE
ALL THREE BOXES CONTAIN GEMS.,THE OTHER TWO BOXES CONTAIN GEMS.,THIS BOX CONTAINS GEMS.,BLACK
THIS BOX IS THE BLACK BOX.,THIS BOX IS THE BLUE BOX.,THE BOX THAT CLAIMS TO BE BLACK HAS THE GEMS.,BLUE
THERE ARE FOUR BOXES IN THIS ROOM.,THERE IS ONLY ONE BOX IN THIS ROOM.,THE GEMS ARE IN THE TRUE BOX.,BLACK
THIS IS THE BLACK BOX.,THIS IS THE BLACK BOX.,THE BLACK BOX IN NOT EMPTY.,BLACK
THE BLACK BOX CONTAINS GEMS.,THIS BOX AND THE BLUE BOX ARE EMPTY.,ALL THREE BOXES ARE EMPTY.,BLACK
THIS STATEMENT APPEARS ON ANOTHER BOX.,THE BLUE BOX IS EMPTY.,THIS STATEMENT APPEARS ON ANOTHER BOX.,BLUE
THERE ARE THREE BOXES IN THIS ROOM.,TWO BOXES IN THIS ROOM ARE EMPTY.,THIS BOX IS ONE OF THE EMPTY BOXES.,BLACK
THIS BOX IS THE MIDDLE BOX.,THE GEMS ARE IN THE MIDDLE BOX.,THIS BOX IS THE MIDDLE BOX.,WHITE
THIS BOX IS BLUE.,THE GEMS ARE IN A TRUE BOX.,THIS BOX IS BLACK.,WHITE
THIS IS THE BLUE BOX.,THE BLUE BOX IS TRUE.,THE BLUE BOX IS EMPTY.,BLUE
THIS BOX IS THE WHITE BOX.,THIS BOX IS THE BLACK BOX.,THE BLUE BOX CONTAINS THE GEMS.,BLUE"""

RULES = """There will always be at least one box which displays only true statements.
There will always be at least one box which displays only false statements.
Only one box has a prize within. The other 2 are always empty."""

bp = buttonpad.ButtonPad(
    """
    `b,`b,`b,`w,`w,`w,`k,`k,`k
    `b, B,`b,`w, W,`w,`k, K,`k
    `b,`b,`b,`w,`w,`w,`k,`k,`k
    I, I, I, I, I, I, I, I, I
    """,
   title="Parlor Puzzle",
   default_bg_color="#f0f0f0",
   default_text_color="black",
   resizable=True,
)
