# Generated by Django 5.2.4 on 2025-10-14 00:00

import django_directory_api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=django_directory_api.models.generate_api_key, help_text='API authentication token (generated automatically)', max_length=64, unique=True)),
                ('name', models.CharField(help_text="Human-readable identifier (e.g., 'GPT-4 Agent', 'Claude API', 'Production Bot')", max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this token is currently active (can be revoked)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this token was created')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this token was used for API authentication', null=True)),
                ('user', models.ForeignKey(help_text='User who owns this API token', on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key', 'is_active'], name='django_dire_key_5ffd45_idx')],
            },
        ),
    ]
