# coding: utf-8

"""
    BugSeq

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PipelineVersion(str, Enum):
    """
    PipelineVersion
    """

    """
    allowed enum values
    """
    LATEST = 'latest'
    V1_DOT_2 = 'v1.2'
    V5_DOT_6 = 'v5.6'
    V5_DOT_7 = 'v5.7'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PipelineVersion from a JSON string"""
        return cls(json.loads(json_str))


