# coding: utf-8

"""
    BugSeq

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UserResponse(BaseModel):
    """
    UserResponse
    """ # noqa: E501
    id: StrictStr
    email: StrictStr
    first_name: StrictStr
    last_name: StrictStr
    created: datetime
    affiliation: StrictStr
    billing_account_id: StrictStr
    pipeline_version: Optional[StrictStr] = None
    pinned_region: Optional[StrictStr] = None
    enabled_features: List[StrictStr]
    __properties: ClassVar[List[str]] = ["id", "email", "first_name", "last_name", "created", "affiliation", "billing_account_id", "pipeline_version", "pinned_region", "enabled_features"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if pipeline_version (nullable) is None
        # and model_fields_set contains the field
        if self.pipeline_version is None and "pipeline_version" in self.model_fields_set:
            _dict['pipeline_version'] = None

        # set to None if pinned_region (nullable) is None
        # and model_fields_set contains the field
        if self.pinned_region is None and "pinned_region" in self.model_fields_set:
            _dict['pinned_region'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "email": obj.get("email"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "created": obj.get("created"),
            "affiliation": obj.get("affiliation"),
            "billing_account_id": obj.get("billing_account_id"),
            "pipeline_version": obj.get("pipeline_version"),
            "pinned_region": obj.get("pinned_region"),
            "enabled_features": obj.get("enabled_features")
        })
        return _obj


