# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from royal_mail_click_and_drop import UpdateOrderStatusRequest

class TestUpdateOrderStatusRequest(unittest.TestCase):
    """UpdateOrderStatusRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateOrderStatusRequest:
        """Test UpdateOrderStatusRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateOrderStatusRequest`
        """
        model = UpdateOrderStatusRequest()
        if include_optional:
            return UpdateOrderStatusRequest(
                order_identifier = 56,
                order_reference = '',
                status = 'new',
                tracking_number = '',
                despatch_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                shipping_carrier = '',
                shipping_service = ''
            )
        else:
            return UpdateOrderStatusRequest(
        )
        """

    def testUpdateOrderStatusRequest(self):
        """Test UpdateOrderStatusRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
