# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from royal_mail_click_and_drop.models.update_order_status_response import UpdateOrderStatusResponse

class TestUpdateOrderStatusResponse(unittest.TestCase):
    """UpdateOrderStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateOrderStatusResponse:
        """Test UpdateOrderStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateOrderStatusResponse`
        """
        model = UpdateOrderStatusResponse()
        if include_optional:
            return UpdateOrderStatusResponse(
                updated_orders = [
                    royal-mail-click-and-drop.models.updated_order_info.UpdatedOrderInfo(
                        order_identifier = 56, 
                        order_reference = '', 
                        status = '', )
                    ],
                errors = [
                    royal-mail-click-and-drop.models.order_update_error.OrderUpdateError(
                        order_identifier = 56, 
                        order_reference = '', 
                        status = '', 
                        code = '', 
                        message = '', )
                    ]
            )
        else:
            return UpdateOrderStatusResponse(
        )
        """

    def testUpdateOrderStatusResponse(self):
        """Test UpdateOrderStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
