# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from royal_mail_click_and_drop import LabelsApi


class TestLabelsApi(unittest.TestCase):
    """LabelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LabelsApi()

    def tearDown(self) -> None:
        pass

    def test_get_orders_label_async(self) -> None:
        """Test case for get_orders_label_async

        Return a single PDF file with generated label and/or associated document(s)
        """
        pass


if __name__ == '__main__':
    unittest.main()
