"""
    EMIL Process Manager

    The EMIL Process Manager API description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eis.process-manager
from eis.process-manager.model.trigger_workflow_request_grpc_dto import TriggerWorkflowRequestGrpcDto


class TestTriggerWorkflowRequestGrpcDto(unittest.TestCase):
    """TriggerWorkflowRequestGrpcDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTriggerWorkflowRequestGrpcDto(self):
        """Test TriggerWorkflowRequestGrpcDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TriggerWorkflowRequestGrpcDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
