ATTRIBUTES = {
    "campfire": {"open", "craft"},
    "composter": {"open", "machine"},
    "furnace": {"open", "machine"},
    "glass key": {"key"},
    "glass lock": {"lock"},
    "left": {"point"},
    "manual press": {"open", "craft"},
    "masonry bench": {"open", "craft"},
    "mushroom shaper": {"open", "craft"},
    "mushroom table": {"store", "table"},
    "player": {"open", "craft"},
    "rabbit adult": {"animal"},
    "rabbit child": {"animal"},
    "sawbench": {"open", "craft"},
    "slime": {"enemy"},
    "slime table": {"store", "table"},
    "small barrel": {"open", "store"},
    "small crate": {"open", "store"},
    "up": {"point"},
    "void convertor": {"open", "machine"},
    "void crate": {"open", "store"},
    "wood crucible": {"open", "machine"},
    "wooden bed": {"sleep"},
    "wooden table": {"store", "table"},
    "workbench": {"open", "craft"},
}
