from .libraryinfo import QSideInfo as QSideInfo
from .qt import QFontDatabase as QFontDatabase, QIcon as QIcon, QObject as QObject, Signal as Signal
from _typeshed import Incomplete

def qLoadResources() -> None: ...

class QIconProvider:
    __cache__: Incomplete
    def __init__(self, theme: str) -> None: ...
    def icon(self, name: str) -> QIcon: ...

class QTheme(QObject):
    __instance__: Incomplete
    __initialized__: bool
    changed: Incomplete
    def __new__(cls, *args, **kwargs): ...
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls) -> QTheme: ...
    def name(self) -> str: ...
    def switch(self, theme: str) -> None: ...
