RESISTANCE = {
    "big rock": 2,
    "bluebell jar": 2,
    "bluebell grown": 1,
    "brick": 1,
    "brick floor": 1,
    "clay": 1,
    "coal": 1,
    "coal ore": 2,
    "composter": 1,
    "copper brick": 3,
    "copper brick floor": 3,
    "furnace": 3,
    "ice": 1,
    "life crystal": 1,
    "manual press": 1,
    "masonry bench": 1,
    "moist dirt": 1,
    "mushroom block": 1,
    "mushroom door": 1,
    "mushroom door open": 1,
    "mushroom floor": 1,
    "mushroom shaper": 2,
    "mushroom table": 1,
    "pebble": 1,
    "potato": 1,
    "potato grown": 1,
    "rabbit adult": 1,
    "rock": 1,
    "sawbench": 1,
    "slime block": 1,
    "slime door": 1,
    "slime door open": 1,
    "slime floor": 1,
    "slime table": 1,
    "stone": 1,
    "stone brick": 1,
    "stone brick floor": 1,
    "stone floor": 1,
    "tree": 1,
}
