# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: synapse_pb/clock_offset.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from synapse_pb import timestamp_pb2 as synapse__pb_dot_timestamp__pb2
from synapse_pb import duration_pb2 as synapse__pb_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsynapse_pb/clock_offset.proto\x12\nsynapse_pb\x1a\x1asynapse_pb/timestamp.proto\x1a\x19synapse_pb/duration.proto\"Y\n\x0b\x43lockOffset\x12$\n\x05stamp\x18\x01 \x01(\x0b\x32\x15.synapse_pb.Timestamp\x12$\n\x06offset\x18\x02 \x01(\x0b\x32\x14.synapse_pb.Durationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'synapse_pb.clock_offset_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLOCKOFFSET._serialized_start=100
  _CLOCKOFFSET._serialized_end=189
# @@protoc_insertion_point(module_scope)
