def word_replace(text: str) -> str: ...
def nyaify(text: str) -> str: ...
def char_replace(text: str) -> str: ...
def stutter(text: str, strength: float) -> str: ...
def emoji(text: str, strength: float) -> str: ...
def tildify(text: str, strength: float) -> str: ...
def uwuify(text: str, *, stutter_strength: float, emoji_strength: float, tilde_strength: float) -> str: ...
