"""`__init__` for `structures` module."""

from ._concrete import (
    DBCDeviceType,
    DBCEvent,
    DBCVolumeFlags,
    DEV_BROADCAST_DEVICEINTERFACE_W,
    DEV_BROADCAST_HDR,
    DEV_BROADCAST_OEM,
    DEV_BROADCAST_PORT_A,
    DEV_BROADCAST_PORT_W,
    DEV_BROADCAST_VOLUME,
    GUID_DEVINTERFACE_COMPORT,
    GUID_DEVINTERFACE_DISK,
    GUID_DEVINTERFACE_PARALLEL,
    GUID_DEVINTERFACE_USB_DEVICE,
    GUID_DEVINTERFACE_USB_HOST_CONTROLLER,
    GUID_DEVINTERFACE_USB_HUB,
    GUID_DEVINTERFACE_VOLUME,
)

__all__ = (
    "DBCDeviceType",
    "DBCEvent",
    "DBCVolumeFlags",
    "DEV_BROADCAST_DEVICEINTERFACE_W",
    "DEV_BROADCAST_HDR",
    "DEV_BROADCAST_OEM",
    "DEV_BROADCAST_PORT_A",
    "DEV_BROADCAST_PORT_W",
    "DEV_BROADCAST_VOLUME",
    "GUID_DEVINTERFACE_COMPORT",
    "GUID_DEVINTERFACE_DISK",
    "GUID_DEVINTERFACE_PARALLEL",
    "GUID_DEVINTERFACE_USB_DEVICE",
    "GUID_DEVINTERFACE_USB_HOST_CONTROLLER",
    "GUID_DEVINTERFACE_USB_HUB",
    "GUID_DEVINTERFACE_VOLUME",
)
