#!/usr/bin/env python3

"""All audio, video and image suffixes."""


AUDIO_SUFFIXES = {  # audio only
    ".3gp",
    ".8svx",
    ".aa", ".aax",
    ".aac",
    ".ac3",
    ".act",
    ".aiff", ".alac", ".m4p", ".movpkg",  # apple
    ".amr",
    ".ape",
    ".au",
    ".awb",
    ".cda",
    ".dss",
    ".dvf", ".msv",  # sony
    ".f4a", ".f4b", ".f4p",
    ".flac",
    ".gsm",
    ".iklax",
    ".ivs",
    ".m4a", ".m4b",
    ".mmf",
    ".mp3", ".mpa", ".mp2", ".mp1", ".m2a", ".m1a",
    ".mpc",
    ".nmf",
    ".oga", ".ogg", ".opus", ".mogg",
    ".ra", ".rm",
    ".sln",
    ".tsa",
    ".tta",
    ".voc",
    ".vox",
    ".wav", ".wv", ".rf64",
    ".wma",
}

IMAGE_SUFFIXES = {
    ".avif",
    ".bmp", ".dib",
    ".exr",
    ".hdr", ".pic",
    ".heic", ".heif",
    ".j2c", ".j2k", ".jp2", ".jpc", ".jpg2", ".jpeg2000", ".jpg2000", ".jpf", ".jpm", ".jpx",
    ".jpeg", ".jpg", ".jpe",
    ".kra",
    ".pbm", ".pgm", ".ppm", ".pxm", ".pnm",
    ".pfm",
    ".png",
    ".psd",
    ".sgi",
    ".sr",  ".ras",
    ".tif", ".tiff",
    ".webp",
    ".xbm",
}

VIDEO_SUFFIXES = {  # audio as well
    ".3g2",
    ".3gp",
    ".asf", "wmv",
    ".avi",
    ".divx",
    ".eov",
    ".f4v",
    ".flv",
    ".gif",
    ".m2p", ".ps", ".mpg", ".mpeg", ".mpv", ".m1v",
    ".m2ts", ".mts",
    ".mk3v",
    ".mkv",
    ".mov", ".qt",
    ".mp4", ".m4v",
    ".mxf",
    ".nut",
    ".ogv", ".ogx",
    ".rmvb",
    ".ts", ".tsv",
    ".vob",
    ".webm",
    ".y4m",
}
