# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.reindex_status import ReindexStatus

class TestReindexStatus(unittest.TestCase):
    """ReindexStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReindexStatus(self):
        """Test ReindexStatus"""
        # inst = ReindexStatus()

if __name__ == '__main__':
    unittest.main()
