# coding: utf-8

"""
    BugSeq

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SampleTypeOutput(str, Enum):
    """
    SampleTypeOutput
    """

    """
    allowed enum values
    """
    METAGENOMIC = 'metagenomic'
    SIXTEEN_S = 'sixteen_s'
    ISOLATE = 'isolate'
    ANY_SAMPLE_TYPE = 'any_sample_type'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SampleTypeOutput from a JSON string"""
        return cls(json.loads(json_str))


