# coding: utf-8

"""
    Platform API

    _OpenAPI specification for the **Platform API** of **Helix**, the nomination platform of ElecLink_  ---  Additional documentation available in the API's [GitHub repository](https://github.com/eleclink-helix/platform-api) 

    The version of the OpenAPI document: 1.2.0
    Contact: team.eleclink@eleclink.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from helix_platform_api_public_client_legacy.models.participant_dashboard_interconnector_capacity_data import ParticipantDashboardInterconnectorCapacityData  # noqa: E501

class TestParticipantDashboardInterconnectorCapacityData(unittest.TestCase):
    """ParticipantDashboardInterconnectorCapacityData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ParticipantDashboardInterconnectorCapacityData:
        """Test ParticipantDashboardInterconnectorCapacityData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ParticipantDashboardInterconnectorCapacityData`
        """
        model = ParticipantDashboardInterconnectorCapacityData()  # noqa: E501
        if include_optional:
            return ParticipantDashboardInterconnectorCapacityData(
                mtu_size = 'MTU_15_MINS',
                mtus = [
                    helix_platform_api_public_client_legacy.models.participant_dashboard_interconnector_capacity_data_mtus.ParticipantDashboardInterconnectorCapacityData_mtus(
                        mtu = '2022-01-04T10:00:00.000Z', 
                        values = [
                            helix_platform_api_public_client_legacy.models.participant_dashboard_interconnector_capacity_data_mtus_values.ParticipantDashboardInterconnectorCapacityData_mtus_values(
                                direction = 'GB_FR', 
                                data = helix_platform_api_public_client_legacy.models.participant_dashboard_interconnector_capacity_data_mtus_values_data.ParticipantDashboardInterconnectorCapacityData_mtus_values_data(
                                    mptc_ntc = 56, 
                                    ntc = 56, ), )
                            ], )
                    ]
            )
        else:
            return ParticipantDashboardInterconnectorCapacityData(
                mtu_size = 'MTU_15_MINS',
                mtus = [
                    helix_platform_api_public_client_legacy.models.participant_dashboard_interconnector_capacity_data_mtus.ParticipantDashboardInterconnectorCapacityData_mtus(
                        mtu = '2022-01-04T10:00:00.000Z', 
                        values = [
                            helix_platform_api_public_client_legacy.models.participant_dashboard_interconnector_capacity_data_mtus_values.ParticipantDashboardInterconnectorCapacityData_mtus_values(
                                direction = 'GB_FR', 
                                data = helix_platform_api_public_client_legacy.models.participant_dashboard_interconnector_capacity_data_mtus_values_data.ParticipantDashboardInterconnectorCapacityData_mtus_values_data(
                                    mptc_ntc = 56, 
                                    ntc = 56, ), )
                            ], )
                    ],
        )
        """

    def testParticipantDashboardInterconnectorCapacityData(self):
        """Test ParticipantDashboardInterconnectorCapacityData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
