from ...datamodels.DataModel import DataModel as DataModel
from ...datamodels.wells.Station import Station as Station
from dataclasses import dataclass, field
from strenum import StrEnum

class DeviationSurveyUsageEnum(StrEnum):
    Plan = 'Plan'
    Actual = 'Actual'

class AzimuthReferenceEnum(StrEnum):
    Unknown = 'Unknown'
    TrueNorth = 'TrueNorth'
    MagneticNorth = 'MagneticNorth'
    GridNorth = 'GridNorth'

@dataclass
class Survey(DataModel):
    description: str | None = ...
    azimuth_reference: AzimuthReferenceEnum | None = ...
    azimuth_offset: float | None = ...
    usage: DeviationSurveyUsageEnum | None = ...
    is_default: bool | None = ...
    stations: list[Station] = field(default_factory=list[Station])
    def copy_ids_from(self, source: DataModel): ...
    @property
    def valid_stations(self) -> list[Station]: ...
    def find_md(self, tvd: float, extrapolate: bool = False) -> float | None: ...
    def find_tvd(self, md: float) -> float | None: ...
